name: "AWS Deploy"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: terraform
      TF_WORKSPACE: my-workspace
      AWS_REGION: "us-east-1"
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Initialization
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_assume_role: "GitHubAction-AssumeRoleWithAction"

      - name: Plan output
        id: output
        if: always()
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        run: |
          echo "### Terraform Summary ðŸš€" >> $GITHUB_STEP_SUMMARY
          echo "* **Format:** \`${{ steps.fmt.outcome }}\`" >> $GITHUB_STEP_SUMMARY
          echo "* **Initialization:** \`${{ steps.init.outcome }}\`" >> $GITHUB_STEP_SUMMARY
          echo "* **Plan:** \`${{ steps.plan.outcome }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Show Plan Details</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```hcl' >> $GITHUB_STEP_SUMMARY
          # Using a Heredoc to handle special characters safely
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          $PLAN
          EOF
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve -input=false
          # Capture the output and save it to GitHub Actions state
          echo "REPO_BUCKET=$(terraform output -raw repo_bucket)" >> $GITHUB_OUTPUT

        working-directory: ${{ env.working-directory }}
        env:
          TF_VAR_assume_role: "GitHubAction-AssumeRoleWithAction"

      - name: Deploy Site to S3
        run: |
          # Access the variables from the 'apply' step
          aws s3 sync ./ s3://${{ steps.apply.outputs.REPO_BUCKET }}/git-hub/ --delete 

      